services:
    smpl_frm:
        build:
            context: ../
            dockerfile: docker/images/Dockerfile
        ports:
         - "8321:8000"
        environment:
            - SMPL_FRM_ASSET_DIRECTORIES=/app/library,/app/assets
            - SMPL_FRM_EXTERNAL_PORT=8321
            - SMPL_FRM_HOST=localhost
            - PYTHONUNBUFFERED=1
        volumes:
            - /example/local/library/here:/app/library
