from unittest import TestCase
from unittest.mock import Mock
import pandas as pd

from src.smplfrm.smplfrm.plugins.tides.tides import TidesPlugin


class TestTidesPlugin(TestCase):

    def setUp(self):
        self.service = TidesPlugin()
        # clear any data in the cache
        self.service.delete()
        self.service.get_tide_data = TestTidesPlugin.get_test_data

    def test_parse_tide_data(self):
        # assert the cache is empty
        self.assertIsNone(self.service.read())
        tides = self.service.parse_tide_data(TestTidesPlugin.get_test_data())
        self.assertEqual(len(tides), 27)
        h_or_l = ["H", "L"]
        h_count = 14
        l_count = 13
        # assert each one has a H or L and a value
        for k, v in tides.items():
            self.assertIn(v[0], h_or_l)
            if v[0] == "H":
                h_count -= 1
            elif v[0] == "L":
                l_count -= 1
            else:
                assert False
            self.assertTrue(isinstance(v[1], float))
        self.assertTrue(h_count == 0)
        self.assertTrue(l_count == 0)

        # assert the cache has data in it now
        self.assertIsNotNone(self.service.read())

    def test_get_for_display(self):
        # tides w/o redis
        self.service.read = self.get_test_data_for_display

        tides = self.service.get_for_display()
        self.assertEqual(len(tides), 4)

        self.assertEqual(tides["1759280820000"]["type"], "H")
        self.assertEqual(tides["1759280820000"]["height"], 5.78)
        self.assertEqual(tides["1759308240000"]["type"], "L")
        self.assertEqual(tides["1759308240000"]["height"], 0.78)
        self.assertEqual(tides["1759334820000"]["type"], "H")
        self.assertEqual(tides["1759334820000"]["height"], 4.833)
        self.assertEqual(tides["1759351260000"]["type"], "L")
        self.assertEqual(tides["1759351260000"]["height"], 3.891)

    def test_get_for_display_no_data(self):
        """
        Asserts that when no tide data is found None is returned
        :return:
        """
        self.service.read = lambda: None
        mock_get_tide_data = Mock()
        mock_get_tide_data.return_value = None
        self.service.get_tide_data = mock_get_tide_data
        tides = self.service.get_for_display()
        self.assertTrue(tides is None)

    def get_test_data_for_display(self):
        dataframe = pd.DataFrame(
            {
                "v": {
                    "1759280820000": 5.78,
                    "1759308240000": 0.78,
                    "1759334820000": 4.833,
                    "1759351260000": 3.891,
                },
                "type": {
                    "1759280820000": "H",
                    "1759308240000": "L",
                    "1759334820000": "H",
                    "1759351260000": "L",
                },
            }
        )
        return self.service.parse_tide_data(dataframe)

    @staticmethod
    def get_test_data(*args, **kwargs):
        """
        This data was generated by using
        a dataframe returned from noaa_coops
        using df.to_json()
        :return:
        """
        dataframe = pd.DataFrame(
            {
                "v": {
                    "1759280820000": 5.78,
                    "1759308240000": 0.78,
                    "1759334820000": 4.833,
                    "1759351260000": 3.891,
                    "1759371900000": 5.841,
                    "1759398060000": 0.539,
                    "1759423500000": 5.169,
                    "1759441680000": 3.352,
                    "1759462380000": 6.038,
                    "1759487280000": 0.321,
                    "1759511760000": 5.582,
                    "1759531320000": 2.627,
                    "1759552440000": 6.28,
                    "1759576200000": 0.216,
                    "1759599960000": 6.067,
                    "1759620600000": 1.784,
                    "1759642140000": 6.482,
                    "1759664880000": 0.279,
                    "1759688100000": 6.597,
                    "1759709700000": 0.901,
                    "1759731780000": 6.592,
                    "1759753560000": 0.527,
                    "1759776360000": 7.125,
                    "1759798860000": 0.067,
                    "1759821300000": 6.578,
                    "1759842180000": 0.938,
                    "1759864680000": 7.586,
                },
                "type": {
                    "1759280820000": "H",
                    "1759308240000": "L",
                    "1759334820000": "H",
                    "1759351260000": "L",
                    "1759371900000": "H",
                    "1759398060000": "L",
                    "1759423500000": "H",
                    "1759441680000": "L",
                    "1759462380000": "H",
                    "1759487280000": "L",
                    "1759511760000": "H",
                    "1759531320000": "L",
                    "1759552440000": "H",
                    "1759576200000": "L",
                    "1759599960000": "H",
                    "1759620600000": "L",
                    "1759642140000": "H",
                    "1759664880000": "L",
                    "1759688100000": "H",
                    "1759709700000": "L",
                    "1759731780000": "H",
                    "1759753560000": "L",
                    "1759776360000": "H",
                    "1759798860000": "L",
                    "1759821300000": "H",
                    "1759842180000": "L",
                    "1759864680000": "H",
                },
            }
        )

        return dataframe
