# Generated by Django 4.2.17 on 2024-12-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smplfrm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
