# Generated by Django 6.0.3 on 2026-03-13 02:45

import smplfrm.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smplfrm", "0005_imagemetadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=smplfrm.models.base.generate_external_id, max_length=16
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("display_date", models.BooleanField(default=True)),
                ("display_clock", models.BooleanField(default=True)),
                ("image_refresh_interval", models.PositiveIntegerField(default=30000)),
                (
                    "image_transition_interval",
                    models.PositiveIntegerField(default=10000),
                ),
                ("image_zoom_effect", models.BooleanField(default=True)),
                (
                    "image_transition_type",
                    models.CharField(
                        choices=[
                            ("random", "Random"),
                            ("fade", "Fade"),
                            ("slide-left", "Slide Left"),
                            ("slide-right", "Slide Right"),
                            ("zoom", "Zoom"),
                            ("none", "None"),
                        ],
                        default="random",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "config",
            },
        ),
    ]
