# Generated by Django 6.0.3 on 2026-03-14 03:15

import smplfrm.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smplfrm", "0006_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=smplfrm.models.base.generate_external_id, max_length=16
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("reset_image_count", "Reset Image Count"),
                            ("clear_cache", "Clear Cache"),
                            ("rescan_library", "Rescan Library"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "task",
            },
        ),
    ]
