# Generated by Django 6.0.3 on 2026-03-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smplfrm", "0007_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="image_cache_timeout",
            field=models.PositiveIntegerField(default=300),
        ),
    ]
