# Generated by Django 6.0.3 on 2026-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smplfrm", "0009_config_add_name_and_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
