# Generated by Django 6.0.3 on 2026-03-28 02:20

import smplfrm.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smplfrm", "0010_add_config_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=smplfrm.models.base.generate_external_id, max_length=16
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "plugin",
            },
        ),
        migrations.AddField(
            model_name="config",
            name="force_date_from_path",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="config",
            name="image_fill_mode",
            field=models.CharField(
                choices=[
                    ("blur", "Blur"),
                    ("border", "Border"),
                    ("zoom_to_fill", "Zoom to Fill"),
                ],
                default="blur",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="plugins",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="config",
            name="timezone",
            field=models.CharField(default="America/Los_Angeles", max_length=50),
        ),
    ]
