# Generated by Django 6.0.8 on 2026-09-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smplfrm", "0011_add_plugin_model_and_config_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("reset_image_count", "Reset Image Count"),
                    ("clear_cache", "Clear Cache"),
                    ("rescan_library", "Rescan Library"),
                    ("preload_image_cache", "Preload Image Cache"),
                ],
                max_length=30,
            ),
        ),
    ]
