services:
    smpl_frm:
        build:
            context: ../../
            dockerfile: ./docker/images/Dockerfile
        ports:
         - "8321:8321"
        env_file:
          - config.env
        volumes:
            - ../../library:/app/library
            - db:/app/src/smplfrm/db
        networks:
          - smpl_frm_net
    smpl_frm_celery:
        command: [ "make", "start-celery"]
        build:
            context: ../../
            dockerfile: ./docker/images/Dockerfile
        env_file:
          - config.env
        volumes:
            - ../../library:/app/library
            - db:/app/src/smplfrm/db
        networks:
          - smpl_frm_net
    smpl_frm_celery_beat:
        command: [ "make", "start-celery-beat"]
        build:
            context: ../../
            dockerfile: ./docker/images/Dockerfile
        env_file:
          - config.env
        volumes:
            - ../../library:/app/library
            - db:/app/src/smplfrm/db
        networks:
          - smpl_frm_net

    cache:
      extends:
        file: services.yaml
        service: cache

networks:
  smpl_frm_net:

volumes:
  cache:
    driver: local
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/ricky/dev/smplFrm/docker/data
      o: bind