services:
    smpl_frm:
        build:
            context: ../../
            dockerfile: ./docker/images/Dockerfile
        ports:
         - "8321:8321"
        env_file:
          - config.env
        volumes:
            - ../../library:/app/library
            - db:/app/src/smplfrm/db
        depends_on:
          - cache
        networks:
          - smpl_frm_net

    cache:
        image: redis:7.4.1-alpine
        restart: always
        ports:
          - "6379:6379"
        volumes:
          - cache:/data
        networks:
          - smpl_frm_net

networks:
  smpl_frm_net:

volumes:
  cache:
    driver: local
  db:
    driver: local
