name: Python CI

on:
  push:
    branches: [ main, djangoMain]
  pull_request:
    branches: [ main, djangoMain ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make packages
      - name: Run tests
        run: make test
      - name: Report test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/test-reports/